### ISSUE TITLE
Instagram example

### ISSUE THREAD

**Issue by 89z** [serguun42/Social-Picker-API#2]
Do you have an example program available?

**Comment by serguun42** [comment]
Yes, I do – [social.serguun42.ru](https://social.serguun42.ru/). It requires an account, but you can easily create one (info popup on the startup will guide you).
![image](https://user-images.githubusercontent.com/27496498/152828529-77b7569a-a5b1-4566-8c69-25f2259fd664.png)

After signing up I'll give you permission and there you'll go. All above is just for sake of security.

-------------------

Or you can spin up your instance ([how to in README](https://github.com/serguun42/Social-Picker-API#commands--how-to-use))

> 1. `git clone`
> 2. Install necessary dependencies – `npm i --production`
> 3. Run production server – `npm run production`
> 
> After launching you can access Picker with fetching `curl http://localhost:8080/?url=__LINK_TO_ANY_POST__` (change `8080` to real port you specified in config/service.json)

No tokens are needed for Instagram and providing cookies is optional.

-------------------

And there is 3rd option: adding `?__a=1` to URL of any (_not private_) Instagram post will give you full info about it in JSON. Example: https://www.instagram.com/p/CZkjkTsDrKA/?__a=1

-------------------

I hope it will help

**Comment by serguun42** [comment]
Closing this issue, because it's done 👉🏻 https://github.com/89z/mech/blob/master/instagram/graph.go#L46

**Comment by 89z** [comment]
Please dont link to my code. I didnt ask for an example of my own code, I asked for an example from this repo.

**Comment by serguun42** [comment]
You asked for 'example program', I gave the link to it. And gave instruction how to spin-up new instance of this program to see how it works. And then I told about adding `?__a=1` to URL.

Day passed – no reply about how it's going. But it was done, so I closed the issue. What should I have done? Close without any reason? Or leave this issue be opened forever?

**Comment by 89z** [comment]
> What should I have done?

What you should NOT do, is go looking through a persons code, when they asked for information about YOUR code. I cant possibly imagine how you could think thats appropriate.

If you have an issue with my code, then post on my repo. Otherwise, I dont need you to link to my code, I know it exists.

**Comment by serguun42** [comment]
Now I see what's wrong. I'm sorry that I offended. If there was any mentioning notification, I'm sorry for that too. I should not have commented with that link, but I should've asked if anything was unclear.


Anyway, now I understand that you asked for [actual code from this repo](https://github.com/serguun42/Social-Picker-API/blob/master/core/social-parsers.js#L183) works for Instagram:
```javascript
NodeFetch(`https://${url.hostname}${url.pathname}?__a=1`, { … })
```
Just adding `?__a=1` after post's shortcode and then [parsing JSON from response](https://github.com/serguun42/Social-Picker-API/blob/master/core/social-parsers.js#L203):
```javascript
return res.json();
```
After it's done, there begins process of guessing which type of post it is: video only, image only and so on – [starting from this line](https://github.com/serguun42/Social-Picker-API/blob/master/core/social-parsers.js#L222)

Every post attachment goes to `socialPost` ([its type is defined here](https://github.com/serguun42/Social-Picker-API/blob/902ea649ad6539887fd0f4046593a3682f2f1551/types/index.d.ts#L18) along with type of media attachment). And that's all.
